remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Portafolio de Antonio]
description: ["En este espacio presento mis proyectos de Ciencia de Datos."]

---
title: GitHub
permalink: /github/
---

Here you can add your GitHub link, for example:

[GitHub Repository](https://github.com/your-username/your-repo)
