remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Mi Portafolio de Ciencia de Datos]
description: ['Antonio Jimenez Caballero \n En este espacio presento mis proyectos.']

