remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Portafolio de Antonio]
description: ["Bienvenido a mi portafolio de ciencia de datos. Aquí podrás conocer mis proyectos en este campo tan fascinante. Para más detalles, visita los enlaces de cada proyecto."]

