remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Portafolio de Antonio]
description: ["Te doy la bienvenida a mi portafolio de ciencia de datos, donde podrás conocer mis proyectos y experiencias en este campo tan fascinante. Explora mi trabajo y descubre cómo generé valor y obtuve ideas o conocimientos significativos a partir de los datos. Para más detalles, visita los enlaces de cada proyecto."]

